[package]
name = "kube-runtime"
version = "0.52.0"
description = "Kubernetes futures controller runtime"
authors = [
  "Teo Klestrup Röijezon <teo@nullable.se>",
  "clux <sszynrae@gmail.com>",
]
license = "Apache-2.0"
repository = "https://github.com/clux/kube-rs"
keywords = ["kubernetes", "runtime", "reflector", "watcher", "controller"]
categories = ["web-programming::http-client"]
edition = "2018"

[dependencies]
futures = "0.3.8"
kube = { path = "../kube", version = "^0.52.0", default-features = false }
derivative = "2.1.1"
serde = "1.0.118"
smallvec = "1.6.0"
pin-project = "1.0.2"
tokio = { version = "1.0.1", features = ["time"] }
snafu = { version = "0.6.10", features = ["futures"] }
dashmap = "4.0.1"
tokio-util = { version = "0.6.0", features = ["time"] }

[dependencies.k8s-openapi]
version = "0.11.0"
git = "https://github.com/jeffa5/k8s-openapi"
branch = "nano-time"
default-features = false

[features]
default = ["native-tls"]
native-tls = ["kube/native-tls"]
rustls-tls = ["kube/rustls-tls"]

[dev-dependencies]
kube-derive = { path = "../kube-derive", version = "^0.52.0"}
serde_json = "1.0.61"
tokio = { version = "1.0.1", features = ["full", "test-util"] }
rand = "0.8.0"
schemars = "0.8.0"

[dev-dependencies.k8s-openapi]
version = "0.11.0"
git = "https://github.com/jeffa5/k8s-openapi"
branch = "nano-time"
default-features = false
features = ["v1_20"]
